### ISSUE TITLE
Support Ubuntu Linux

### ISSUE THREAD

**Issue by luisdelarosa** [HJianBo/Mqtt#1]
I saw this as a TODO in the README. I was previously using Aphid but that library has been deprecated. I'd like to support a 100% pure Swift MQTT library for Hacktoberfest. I use MQTT in my IoT work and am currently utilizing mosquitto clients at the command line.

I just tried running this on Ubuntu MATE 16.04 on Raspberry Pi 3 (ARM) and found several compile errors due to DispatchQueue. I also have access to Ubuntu 16.04 x86 server instances on Digital Ocean for testing.

**Comment by HJianBo** [comment]
Thanks for your attention to this project ！ 

fixed on **0.2.0**
